### ISSUE TITLE
Star Info plugin is no longer accurate since the latest OSRS update

### ISSUE THREAD

**Issue by pnobbe** [pwatts6060/runelite-plugins#14]
Latest update (as of 20/09/2023) saw some changes to Shooting Stars, particularly where they now no longer deplete faster with multiple people mining them.

Understandably so, this broke the Star Info plugin. A fix would be very much appreciated.

https://secure.runescape.com/m=news/poll-80--shooting-stars-changes?oldschool=1

**Comment by pwatts6060** [comment]
I've updated the plugin. The changes are awaiting approval. The T9 time isn't accurate yet but T8 and lower should be for time estimations of layers. Number of miners is fixed and was broken because of animation changes for mining stars so the plugin didn't know anyone was mining. 

If I find a T9 star first I'll be able to get the accurate T9 time but considering how rare that is for me and for plugin users, being off by 30 seconds or so isn't a big deal.

**Comment by pwatts6060** [comment]
On 2nd look, it seems the timers are not constant and there is some variability which is very unfortunate. If anyone is interested in helping collect data let me know here. It would require running the plugin in development mode with some new code I can provide to log times when mining stars. I think I'm going to collect times and just use the average as the estimate.

**Comment by Supinic** [comment]
> If anyone is interested in helping collect data let me know here

Yea I can help out, I managed (with help from others) to set up a dev mode shadowjar with the logs from 8c4a66cb95709b7dace28ba9f52f81aa9850e8e2 put back in. I'm collecting some data already as I AFK shooting stars a fair bit, but if there's more I can do just lemme know.

**Comment by brads93** [comment]
> On 2nd look, it seems the timers are not constant and there is some variability which is very unfortunate. If anyone is interested in helping collect data let me know here. It would require running the plugin in development mode with some new code I can provide to log times when mining stars. I think I'm going to collect times and just use the average as the estimate.

I'd be very happy to help if needed using instructions on how to setup dev mode.

**Comment by pwatts6060** [comment]
[stardata.xlsx](https://github.com/pwatts6060/runelite-plugins/files/12765991/stardata.xlsx)
@brads93 @Supinic You can uncomment the code that displays some data and fill out this table if you want. First column is just a unique id for the star that you get the same data from. Second column is the tier and third column is the time in ticks that you get told in the chatbox or intellij console. The tier in the chatbox is one lower than it actually is so if it says T4 in chatbox it's actually T5 time. You can ignore the summary data; the formulas don't auto update with more data. I can compile the data everyone gets later hopefully.

**Comment by pwatts6060** [comment]
Also the star plugin has been updated and should be working fine but the estimator will be off a bit until we have better data. I have a theory that jagex coded the star depletion with literal 2 players with 99 mining and dragon pickaxes as they said in the blog which would explain the randomness and also be backed up by the constant 2402 tick time for T1 stars because T1 stars are the only tier with 100% success rate for getting dust at T1 with 99 mining. So when I get time I will restore my old code and test this out and see how accurate it is.

**Comment by Supinic** [comment]
@pwatts6060 I uploaded some of my data to this gist: https://gist.github.com/Supinic/ca7397935f7e6ee41feeffe11551e529

It seems to be mostly accurate with the 2x 99 mining simulation. I'll keep logging more data if needed, and I'll be checking the updated plugin's accuracy as well, after this weekend.

**Comment by pwatts6060** [comment]
Thanks everyone for the data. Someone from star miners reached out and got 50 times for each star which should be sufficient. The times were in minutes/seconds so will be some rounding error but it's insignificant to the overall variance in times. Summary of the data for those curious:
![image](https://github.com/pwatts6060/runelite-plugins/assets/30028569/00ad1707-b624-4d97-b00c-99bf3e9db125)
![image](https://github.com/pwatts6060/runelite-plugins/assets/30028569/74526e64-c080-481c-b492-fe1d03dc1c4f)
