### ISSUE TITLE
Instant Idle Notify not triggering after fletching headless arrows

### ISSUE THREAD

**Issue by WhatATopic** [pwatts6060/runelite-plugins#24]
I was combining feathers and arrow shafts to make headless arrows and noticed that Instant Idle Notify isn't sending a notification once I am done fletching the set.

**Comment by pwatts6060** [comment]
So the reason this probably happens is because instant idle notifier works by seeing the changes in your inventory and just intuits processing actions, they aren't defined specifically so it doesn't understand the concept that arrows are made in batches of 10. It looks for identical inventory changes equal intervals apart at least 3 times and will ping you when you can't do this anymore because you have no supplies left to do so. So I believe it would only ping you when you ran out of arrows/shafts completely. 

I don't have a fix for this as it goes beyond the scope of the plugin. However, "Action Progress" and "Efficient Fletching" are both useful for this instead.
